# Generated by Django 3.2 on 2024-03-05 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
