# Generated by Django 3.2 on 2024-03-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240311_1728'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_username_email',
        ),
    ]
