# Generated by Django 3.2 on 2024-03-11 14:28

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(help_text='Год выпуска произведения не может быть больше текущего.', validators=[reviews.validators.validate_year], verbose_name='Год выпуска'),
        ),
    ]
